apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-image-updater-v2
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater-v2
    app.kubernetes.io/part-of: argocd
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
      - update
      - patch

  - apiGroups:
      - ""
    resources:
        - secrets
    verbs:
      - get
      - list

  - apiGroups:
      - ""
    resources:
      - configMaps
    verbs:
      - get
      - list
      - create
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-image-updater-v2
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater-v2
    app.kubernetes.io/part-of: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-image-updater-v2
subjects:
  - kind: ServiceAccount
    name: argocd-image-updater-v2
    namespace: argocd