apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-service.yaml
  - postgres-external.yaml
  - postgres-statefulset.yaml

labels:
  - includeSelectors: true
    pairs:
      app: postgres
      component: database