apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argocd-image-updater
  namespace: argocd

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: argocd-image-updater
      app.kubernetes.io/part-of: argocd

namespace: argocd