apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: default
  labels:
    app.kubernetes.io/name: inventory-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: inventory-service
  ports:
    - port: 8075
      targetPort: 8088
      nodePort: 30091