apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: default
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/cart_db"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"