apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - inventory-service-deployment.yaml
  - inventory-service-configmap.yaml
  - inventory-service-connect.yaml
  - inventory-service-secret.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: inventory-service
      app.kubernetes.io/component: microservice